# Importing and Reading the data

In [ ]:
#import libraries
from sklearn.datasets import load_files
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RandomizedSearchCV 
import matplotlib.pyplot as plt
import numpy as np
import datetime
from datetime import date, timedelta
import pandas as pd
import seaborn as sns
from google.colab import drive
! pip install pattern
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import pattern
from pattern.en import lemma, lexeme

In [ ]:
# pick data from google drive 
drive.mount('/content/gdrive')
path = "/content/gdrive/MyDrive/Noticias_Premier_League/"
path2= "/content/gdrive/MyDrive/finaldataset.csv"

#path = '/content/gdrive/MyDrive/Noticias_Premier_League'
#path2 = '/content/gdrive/MyDrive/csv_files/finaldataset.csv'



Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


# Preparing Data

## Create functions to use in DataFrame


In [ ]:
# Create function to change de format of date
def change_data(v,x,d):
  if len(v[d][x])==8:
    year = '2'+'0'+v[d][x][6]+v[d][x][7]
    month = v[d][x][3]+ v[d][x][4]
    day = v[d][x][0]+ v[d][x][1]
    date = year+'-'+month+'-'+day
    return date
  elif len(v[d][x])==10:
      year = v[d][x][6]+v[d][x][7]+v[d][x][8]+v[d][x][9]
      month = v[d][x][3]+ v[d][x][4]
      day = v[d][x][0]+ v[d][x][1]
      date = year+'-'+month+'-'+day
      return date


In [ ]:
# Create function to apply dummies
def dummies(resultado_d,x):
  if x == 'H':
    resultado_d.append(1)
  elif x=='D':
    resultado_d.append(2)
  elif x=='A':
    resultado_d.append(3)
    

In [ ]:
# Create a function to pick news ten days ago the game 
def get_news(dataframe,x,timev,casa):
  time = dataframe[casa][x] 
  vetor_resultado = []
  if time in timev:
    vetor_noticias=[]
    arquivo_noticias = times[time]
    data_atual = date.fromisoformat(dataframe['Date'][x])
    for y in range (1,11):
      data_analisada = data_atual - timedelta(days=y)
      data = data_analisada.isoformat()
      n_atual =arquivo_noticias.loc[arquivo_noticias['date']==data]
      vetor = np.array(n_atual)
      for k in range (0,len(vetor)):
          texto = ''
          for h in range(3,6):
            texto = texto+''+vetor[k][h]
          vetor_noticias.append(texto)
    data_frame_vetor = pd.DataFrame(vetor_noticias)
    data_frame_vetor.drop_duplicates(inplace = True)
    vetor_resultado = np.array(data_frame_vetor)
  return vetor_resultado

##Create dataframes using created fuctions in data


In [ ]:
## tirar esse unnamed (quando ler o df, fazer index_col = [0])

In [ ]:
# Create dataframe with date of games and replace abbreviations of teams
dfp = pd.read_csv(path2, index_col = [0])
dfp.replace('Man United','Manchester United',inplace=True)
dfp.replace ('Man City','Manchester City',inplace=True)
dfp


Date         HomeTeam  ... DiffFormPts  DiffLP
0       19/08/00         Charlton  ...    0.000000     0.0
1       19/08/00          Chelsea  ...    0.000000    -4.0
2       19/08/00         Coventry  ...    0.000000     2.0
3       19/08/00            Derby  ...    0.000000     1.0
4       19/08/00            Leeds  ...    0.000000   -10.0
...          ...              ...  ...         ...     ...
7595  26/07/2020        Leicester  ...   -0.105263     3.0
7596  26/07/2020  Manchester City  ...    0.315789     1.0
7597  26/07/2020        Newcastle  ...   -0.210526    11.0
7598  26/07/2020      Southampton  ...    0.052632    16.0
7599  26/07/2020         West Ham  ...    0.026316    10.0

[7600 rows x 46 columns]

In [ ]:
# apply change data in dfp
for x in range (0,len(dfp)):
  dfp['Date'][x]=change_data(dfp,x,'Date')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
# Separate target
resultado = dfp['FTR']

In [ ]:
# apply dummies in results
resultado_d = []
for y in resultado:
  dummies(resultado_d,y)

In [ ]:
# Create Features NoticiasHomeTeam and NoticiasAway
noticias_home = []
noticias_away = []
for x in range(0,len(resultado_d)):
  noticias_home.append('ok')
  noticias_away.append('ok')

In [ ]:
# Create DataFrame with news and results of games 
dataframer ={'Date':dfp['Date'],'HomeTeam':dfp['HomeTeam'],'AwayTeam':dfp['AwayTeam'],'Resultado':resultado_d,'Noticias Home':noticias_home,'Noticias Away':noticias_away}
dataframerpd = pd.DataFrame(dataframer)
dataframerpd.drop_duplicates(inplace = True)
dataframerpd

Date         HomeTeam  ... Noticias Home  Noticias Away
0     2000-08-19         Charlton  ...            ok             ok
1     2000-08-19          Chelsea  ...            ok             ok
2     2000-08-19         Coventry  ...            ok             ok
3     2000-08-19            Derby  ...            ok             ok
4     2000-08-19            Leeds  ...            ok             ok
...          ...              ...  ...           ...            ...
7595  2020-07-26        Leicester  ...            ok             ok
7596  2020-07-26  Manchester City  ...            ok             ok
7597  2020-07-26        Newcastle  ...            ok             ok
7598  2020-07-26      Southampton  ...            ok             ok
7599  2020-07-26         West Ham  ...            ok             ok

[7600 rows x 6 columns]

In [ ]:
# Create dataframes news of teams
team0=pd.read_csv(path + 'Arsenal FC.csv' )
team1=pd.read_csv(path + 'Aston Villa.csv' )
team2=pd.read_csv(path + 'Brighton &amp; Hove Albion.csv' )
team3=pd.read_csv(path + 'Burnley FC.csv' )
team4=pd.read_csv(path + 'Chelsea FC.csv' )
team5=pd.read_csv(path + 'Crystal Palace.csv' )
team6=pd.read_csv(path + 'Everton FC.csv' )
team7=pd.read_csv(path + 'Fulham FC.csv' )
team8=pd.read_csv(path + 'Leeds United.csv' )
team9=pd.read_csv(path + 'Leicester City.csv' )
team10=pd.read_csv(path + 'Liverpool FC.csv' )
team11=pd.read_csv(path + 'Manchester City.csv' )
team12=pd.read_csv(path + 'Manchester United.csv' )
team13=pd.read_csv(path + 'Newcastle United.csv' )
team14=pd.read_csv(path + 'Sheffield United.csv' )
team15=pd.read_csv(path + 'Southampton FC.csv' )
team16=pd.read_csv(path + 'Tottenham Hotspur.csv' )
team17=pd.read_csv(path + 'West Bromwich Albion.csv' )
team18=pd.read_csv(path + 'West Ham United.csv' )
team19=pd.read_csv(path + 'Wolverhampton Wanderers.csv' )

In [ ]:
# Create diconary relating teams with yours dataframes 
times = {'Arsenal FC':team0,'Aston Villa':team1,'Brighton &amp; Hove Albion':team2,'Burnley FC':team3,'Chelsea FC':team4, 'Crystal Palace':team5,'Everton FC':team6,'Fulham FC':team7,'Leeds United':team8,'Leicester City':team9,'Liverpool FC':team10,'Manchester City':team11,'Manchester United':team12,'Newcastle United':team13,'Sheffield United':team14,'Southampton FC':team15,'Tottenham Hotspur':team16,'West Bromwich Albion':team17,'West Ham United':team18,'Wolverhampton Wanderers':team19}
times_vetor = list(times.keys())

In [ ]:
# Create a Dataframe with games as from 2013
df = dataframerpd[4758:]
df.reset_index(drop = True, inplace= True)
df

Date         HomeTeam  ... Noticias Home  Noticias Away
0     2013-01-01  Manchester City  ...            ok             ok
1     2013-01-01      Southampton  ...            ok             ok
2     2013-01-01          Swansea  ...            ok             ok
3     2013-01-01        Tottenham  ...            ok             ok
4     2013-01-01        West Brom  ...            ok             ok
...          ...              ...  ...           ...            ...
2837  2020-07-26        Leicester  ...            ok             ok
2838  2020-07-26  Manchester City  ...            ok             ok
2839  2020-07-26        Newcastle  ...            ok             ok
2840  2020-07-26      Southampton  ...            ok             ok
2841  2020-07-26         West Ham  ...            ok             ok

[2842 rows x 6 columns]

In [ ]:
# apply data change in news
for x in times_vetor:
  time = times[x]
  for y in range(0,len(time)):
    time['date'][y]=change_data(time,y,'date')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


In [ ]:
#Add HomeTeam and AwayTeam news
for x in range (0,len(df)):
    df['Noticias Home'][x]=get_news(df,x,times_vetor,'HomeTeam')
    df['Noticias Away'][x]=get_news(df,x,times_vetor,'AwayTeam') 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.htm

# Create a fuction to generate a vector that will be use in TfidfVectorizer

In [ ]:
def vetor_lemma(df):
# Create a vetor with news to use in TfidfVectorizer  
  vetor_news = []
  for x in range(0,len(df)):
     vetor_news.append(df['Noticias Home'][x])
     vetor_news.append(df['Noticias Away'][x])
     vector_news_clean = []
  # Clean text of vetor_news
  clean= ['0','1','2','3','4','5','6','7','8','9','@','©','&','/','\"','-']
  for x in range (0,len(vetor_news)):
      add = ''
      if vetor_news[x] is not np.nan:
          for y in range (0,len(vetor_news[x])):
              if(vetor_news[x][y] not in clean):
                  add = add + vetor_news[x][y]
      vector_news_clean.append(add)
  # Drop duplicates in vector_news_clean
  vetor = list(dict.fromkeys(vector_news_clean))
  vector_train =[]
  # Apply lemmatization
  for x in range (0,len(vetor)):
      vector_train.append(" ".join([lemma(wd) for wd in vetor[x].split()]))
  return vector_train

# Create and apply models with First approach to create dictionary with TfidfVectorizer

## Transform news in lists with only one text


In [ ]:
df['Noticias Away'][2837]

array([['European football and survival up for grabs in Premier League finaleThe Premier League will finally reach the end of its longest season on Sunday with plenty still on the line at both ends of the table.Manchester United and Leicester face each other in a shootout for a place in the Champions League next season with Chelsea also hoping to secure their place in the top four. Wolves and Tottenham are vying for one place in the Europa League. And at the bottom it could not be closer with one goal separating Aston Villa just outside the relegation zone from Watford in the bottom three, while Bournemouth also have a chance of beating the drop. Leicester fell out of the top four for the first time since September in midweek after a run of three wins in 13 games either side of the coronavirus shutdown. However, United\'s and Chelsea\'s failures to win on Wednesday means the door is still open for Brendan Rodgers\'s men to salvage all the good work they did early in the season with vic

In [ ]:
# Transform the vectos of HomeTeam in a list with one text
for x in range(0,len(df)):
  textos = ' '
  for y in range(0,len(df['Noticias Home'][x])):
    atual= df['Noticias Home'][x][y][0]
    textos = textos +''+atual
  df['Noticias Home'][x] = textos

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)


In [ ]:
# Transform the vectos of AwayTeam in a list with one text
for x in range(0,len(df)):
  textos = ' '
  for y in range(0,len(df['Noticias Away'][x])):
    atual= df['Noticias Away'][x][y][0]
    textos = textos +''+atual
  df['Noticias Away'][x] = textos

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)


In [ ]:
df

Date  ...                                      Noticias Away
0     2013-01-01  ...                                                   
1     2013-01-01  ...                                                   
2     2013-01-01  ...                                                   
3     2013-01-01  ...                                                   
4     2013-01-01  ...                                                   
...          ...  ...                                                ...
2837  2020-07-26  ...   European football and survival up for grabs i...
2838  2020-07-26  ...                                                   
2839  2020-07-26  ...                                                   
2840  2020-07-26  ...   Wolves bolster Europa League bid, Blades blun...
2841  2020-07-26  ...                                                   

[2842 rows x 6 columns]

In [ ]:
df['Noticias Away'][2837]

' European football and survival up for grabs in Premier League finaleThe Premier League will finally reach the end of its longest season on Sunday with plenty still on the line at both ends of the table.Manchester United and Leicester face each other in a shootout for a place in the Champions League next season with Chelsea also hoping to secure their place in the top four. Wolves and Tottenham are vying for one place in the Europa League. And at the bottom it could not be closer with one goal separating Aston Villa just outside the relegation zone from Watford in the bottom three, while Bournemouth also have a chance of beating the drop. Leicester fell out of the top four for the first time since September in midweek after a run of three wins in 13 games either side of the coronavirus shutdown. However, United\'s and Chelsea\'s failures to win on Wednesday means the door is still open for Brendan Rodgers\'s men to salvage all the good work they did early in the season with victory on

In [ ]:
df_target = df['Resultado']

## Divide data in train and test and create vector to apply in TfidfVectorizer

In [ ]:
# Divide data in training and test
X_train, X_test, y_train, y_test = train_test_split(df,df_target, test_size=0.3, random_state=0,stratify= df_target)

In [ ]:
X_train.reset_index(drop = True,inplace = True)
y_train.reset_index(drop = True,inplace = True)
X_test.reset_index(drop = True,inplace = True)
y_test.reset_index(drop = True,inplace = True)

### Create a vector to use in train

In [ ]:
vector_train = vetor_lemma(X_train)

## Apply TfidfVectorizer

### Vectorizer for training 

In [ ]:
# Fit vectorizer for train
vectorizer_train = TfidfVectorizer(stop_words={'english'},max_features=2000)
vectorizer_train.fit(vector_train)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=2000,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words={'english'}, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [ ]:
print(vectorizer_train.get_feature_names())
len(vectorizer_train.get_feature_names())

['aaron', 'ability', 'able', 'about', 'above', 'absence', 'absent', 'absolutely', 'abu', 'abuse', 'academy', 'accept', 'accord', 'account', 'accuse', 'achieve', 'achievement', 'acknowledge', 'acros', 'act', 'action', 'adam', 'adamant', 'adapt', 'add', 'added', 'adebayor', 'admit', 'adnan', 'adrift', 'advance', 'advantage', 'affect', 'afford', 'afp', 'african', 'after', 'afternoon', 'again', 'against', 'agbonlahor', 'age', 'agent', 'aggregate', 'ago', 'agree', 'aguero', 'ahead', 'aim', 'ajax', 'alan', 'albion', 'aleksandar', 'alex', 'alexi', 'alive', 'all', 'allardyce', 'allege', 'allen', 'allow', 'alltime', 'almost', 'along', 'alongside', 'already', 'also', 'although', 'alvaro', 'alway', 'amaze', 'ambition', 'amid', 'among', 'amount', 'an', 'analyse', 'and', 'ander', 'anderlecht', 'andre', 'andrea', 'andy', 'anelka', 'anfield', 'angel', 'angle', 'angry', 'ankle', 'anniversary', 'announce', 'another', 'answer', 'anthony', 'antonio', 'any', 'anyone', 'anythe', 'apart', 'apologise', 'appe

2000

In [ ]:
# Transform training news in vectors
tf_noticias_home_train = vectorizer_train.transform(X_train['Noticias Home'])
tf_noticias_away_train = vectorizer_train.transform(X_train['Noticias Away'])

In [ ]:
# Transforms vectors to dense form
tfnoticiash_train = tf_noticias_home_train.todense()
tfnoticiasa_train = tf_noticias_away_train.todense()
X_train_ok = np.hstack((tfnoticiash_train,tfnoticiasa_train))
y_train_ok = np.array(y_train)

### Vectorizer for testing

In [ ]:
# Fit vectorizer for test
vectorizer_test = TfidfVectorizer(stop_words={'english'},max_features=2000)
vectorizer_test.fit(vector_train)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=2000,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words={'english'}, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [ ]:
print(vectorizer_test.get_feature_names())
len(vectorizer_test.get_feature_names())

['aaron', 'ability', 'able', 'about', 'above', 'absence', 'absent', 'absolutely', 'abu', 'abuse', 'academy', 'accept', 'accord', 'account', 'accuse', 'achieve', 'achievement', 'acknowledge', 'acros', 'act', 'action', 'adam', 'adamant', 'adapt', 'add', 'added', 'adebayor', 'admit', 'adnan', 'adrift', 'advance', 'advantage', 'affect', 'afford', 'afp', 'african', 'after', 'afternoon', 'again', 'against', 'agbonlahor', 'age', 'agent', 'aggregate', 'ago', 'agree', 'aguero', 'ahead', 'aim', 'ajax', 'alan', 'albion', 'aleksandar', 'alex', 'alexi', 'alive', 'all', 'allardyce', 'allege', 'allen', 'allow', 'alltime', 'almost', 'along', 'alongside', 'already', 'also', 'although', 'alvaro', 'alway', 'amaze', 'ambition', 'amid', 'among', 'amount', 'an', 'analyse', 'and', 'ander', 'anderlecht', 'andre', 'andrea', 'andy', 'anelka', 'anfield', 'angel', 'angle', 'angry', 'ankle', 'anniversary', 'announce', 'another', 'answer', 'anthony', 'antonio', 'any', 'anyone', 'anythe', 'apart', 'apologise', 'appe

2000

In [ ]:
# Transform test news in vectors
tf_noticias_home_test = vectorizer_train.transform(X_test['Noticias Home'])
tf_noticias_away_test = vectorizer_train.transform(X_test['Noticias Away'])

In [ ]:
# Transforms vectors to dense form
tfnoticiash_test = tf_noticias_home_test.todense()
tfnoticiasa_test = tf_noticias_away_test.todense()
X_test_ok = np.hstack((tfnoticiash_test,tfnoticiasa_test))
y_test_ok = np.array(y_test)

## Logistic Regression

### Use Cross Validation to find best parameters

In [ ]:
log_reg = LogisticRegression(random_state = 42, max_iter = 1000, multi_class = 'ovr')

# defining the search space
space = dict()
space['solver'] = ['lbfgs', 'newton-cg', 'liblinear']
space['penalty'] = ['l1', 'l2', 'elasticnet']
space['C'] = np.arange(10**-4, 20, 0.01)

# training the model and fitting our data to it
rscv = RandomizedSearchCV(log_reg, space, cv = 3, n_jobs = -1, n_iter = 100,verbose=2)
result = rscv.fit(X_train_ok, y_train_ok)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  37 tasks      | elapsed:   17.1s
[Parallel(n_jobs=-1)]: Done 158 tasks      | elapsed:   55.5s
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  1.9min finished


In [ ]:
#best C and regularization
C = rscv.best_params_
c = C['C']
l_penalty = C['penalty']
l_solver = C['solver']

#printing c (best hyperparameter) and penalty
print("C: ", c, "\nPenalty: ", l_penalty)
print("Solver: ", l_solver)

C:  11.4301 
Penalty:  l2
Solver:  newton-cg


### Traning Logistic Regression Model

In [ ]:
reg_log= LogisticRegression(solver= l_solver,random_state=0,penalty= l_penalty,C= c)
reg_log.fit(X_train_ok,y_train_ok)

LogisticRegression(C=11.4301, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='newton-cg', tol=0.0001, verbose=0,
                   warm_start=False)

### Testing Logistic Regression Model

In [ ]:
predictions = reg_log.predict(X_test_ok)

In [ ]:
print(confusion_matrix(y_test_ok,predictions))  
print(classification_report(y_test_ok,predictions))  
print(accuracy_score(y_test_ok, predictions))

[[360   6  25]
 [185   2  15]
 [214   3  43]]
              precision    recall  f1-score   support

           1       0.47      0.92      0.63       391
           2       0.18      0.01      0.02       202
           3       0.52      0.17      0.25       260

    accuracy                           0.47       853
   macro avg       0.39      0.37      0.30       853
weighted avg       0.42      0.47      0.37       853

0.47479484173505276


# Using historic and news in Logistic Regression

## Concatenate historic with news

In [ ]:
# Function to apply dummies in FTR
def dummies_dfpt(d,x,y):
  if d[x][y] == 'H':
    d[x][y]=1
  elif d[x][y]=='D':
    d[x][y]=2
  elif d[x][y]=='A':
    d[x][y]=3

In [ ]:
# Using data as from 2013
dfpt = dfp[4758:]
dfpt.reset_index(drop=True,inplace=True)
for y in range(0,len(dfpt)):
    dummies_dfpt(dfpt,'FTR',y)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: Se

In [ ]:
dfpt

Date         HomeTeam  ... DiffFormPts  DiffLP
0     2013-01-01  Manchester City  ...   -0.100000   -13.0
1     2013-01-01      Southampton  ...   -0.350000    -3.0
2     2013-01-01          Swansea  ...    0.047619    -5.0
3     2013-01-01        Tottenham  ...    0.285714     4.0
4     2013-01-01        West Brom  ...    0.142857     1.0
...          ...              ...  ...         ...     ...
2837  2020-07-26        Leicester  ...   -0.105263     3.0
2838  2020-07-26  Manchester City  ...    0.315789     1.0
2839  2020-07-26        Newcastle  ...   -0.210526    11.0
2840  2020-07-26      Southampton  ...    0.052632    16.0
2841  2020-07-26         West Ham  ...    0.026316    10.0

[2842 rows x 46 columns]

In [ ]:
# Add NoticiasHome and NoticiasAway for dfpt
dfpt['Noticias Home']=df['Noticias Home']
dfpt['Noticias Away']= df['Noticias Away']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
# Drop games whitout news
for x in range(0,len(dfpt)):
  if dfpt['Noticias Home'][x]==' ' and dfpt['Noticias Away'][x]==' ':
      dfpt.drop(index=x,inplace= True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [ ]:
dfpt.reset_index(drop = True, inplace= True)

In [ ]:
# Function to apply Dummies in "HM"and "AM" features
def m_dummies(x,y,w):
    if x[y][w] == 'W':
       x[y][w]=1
    elif x[y][w]=='D':
       x[y][w]=2
    elif x[y][w]=='L':
      x[y][w]=3
    elif x[y][w]=='M':
      x[y][w]=4

In [ ]:
#Apply Dummies in "HM"and "AM" features
new_dummies= ['HM1', 'AM1', 'HM2','AM2', 'HM3', 'AM3', 'HM4', 'AM4', 'HM5', 'AM5']
for x in new_dummies:
  for y in range(0,len(dfpt)):
     m_dummies(dfpt,x,y)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib

In [ ]:
# Features to use in training
columns = ['HS', 'AS', 'HST', 'AST', 'HC', 'AC', 'HF', 'AF', 'HY', 'AY', 'HR', 'AR', 'HTGS', 'ATGS', 'HTGC', 'ATGC', 'HTP', 'ATP', 'HM1', 'AM1', 'HM2',
       'AM2', 'HM3', 'AM3', 'HM4', 'AM4', 'HM5', 'AM5', 'HomeTeamLP', 'AwayTeamLP','HTGD', 'ATGD', 'DiffPts',
       'DiffFormPts', 'DiffLP','Noticias Home','Noticias Away']


In [ ]:
dfpt

Date  ...                                      Noticias Away
0    2013-08-17  ...   Football: Bent joins Fulham on loan from Vill...
1    2013-08-17  ...   Football: Rooney returns as champs United hea...
2    2013-08-18  ...                                                   
3    2013-08-19  ...                                                   
4    2013-08-21  ...   Football: Liverpool complete Cissokho loan si...
..          ...  ...                                                ...
765  2020-07-22  ...                                                   
766  2020-07-26  ...                                                   
767  2020-07-26  ...   European football and survival up for grabs i...
768  2020-07-26  ...                                                   
769  2020-07-26  ...   Wolves bolster Europa League bid, Blades blun...

[770 rows x 48 columns]

## Divide train and test

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(dfpt[columns],dfpt['FTR'], test_size=0.3, random_state=0,stratify=dfpt['FTR'])

In [ ]:
X_train.reset_index(drop = True,inplace = True)
y_train.reset_index(drop = True,inplace = True)
X_test.reset_index(drop = True,inplace = True)
y_test.reset_index(drop = True,inplace = True)

## Create vectors for Tfidf for train and test

In [ ]:
news_train = vetor_lemma(X_train)

### Vectorizer

#### Vectorizer in train news

In [ ]:
# Fit vectorizer for train
vectorizer_train = TfidfVectorizer(stop_words={'english'},max_features=2000)
vectorizer_train.fit(news_train)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=2000,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words={'english'}, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [ ]:
train_home = vectorizer_train.transform(X_train['Noticias Home'])
train_away = vectorizer_train.transform(X_train['Noticias Away'])

In [ ]:
# Transforms vectors to dense form
train_home_d = train_home.todense()
train_away_d = train_away.todense()
X_train_ok = np.hstack((train_home_d,train_away_d))
y_train_ok = np.array(y_train)

#### Vectorizer in test news

In [ ]:
test_home = vectorizer_train.transform(X_test['Noticias Home'])
test_away = vectorizer_train.transform(X_test['Noticias Away'])

In [ ]:
# Transforms vectors to dense form
test_home_d = test_home.todense()
test_away_d = test_away.todense()
X_test_ok = np.hstack((test_home_d,test_away_d))
y_test_ok = np.array(y_train)

### Add news in format of vectores in training 

In [ ]:
# Create dataframe with matrix of news
dftrain = pd.DataFrame(X_train_ok)

In [ ]:
# Drop news in format of words
X_train.drop(columns=['Noticias Home','Noticias Away'],inplace=True)

In [ ]:
X_train =pd.concat((X_train,dftrain),ignore_index=True,axis=1)

In [ ]:
columns_news = ['HS', 'AS', 'HST', 'AST', 'HC', 'AC', 'HF', 'AF', 'HY', 'AY', 'HR', 'AR', 'HTGS', 'ATGS', 'HTGC', 'ATGC', 'HTP', 'ATP', 'HM1', 'AM1', 'HM2',
       'AM2', 'HM3', 'AM3', 'HM4', 'AM4', 'HM5', 'AM5', 'HomeTeamLP', 'AwayTeamLP','HTGD', 'ATGD', 'DiffPts',
       'DiffFormPts', 'DiffLP']

In [ ]:
# back name for columns of historic
y = 0
for x in columns_news:
    X_train.rename(columns={y:x},inplace=True)
    y=y+1

In [ ]:
X_train

HS  AS  HST  AST  HC  ...      4030      4031      4032      4033      4034
0    14  16    6    5   5  ...  0.000000  0.000000  0.000000  0.019349  0.000000
1    10  12    4    7   7  ...  0.000000  0.012222  0.014886  0.000000  0.002975
2    14  19    4    5   6  ...  0.000000  0.000000  0.000000  0.000000  0.000000
3    12   7    6    2   7  ...  0.000000  0.000000  0.000000  0.000000  0.000000
4    12  18    1    7   3  ...  0.000000  0.000000  0.000000  0.000000  0.000000
..   ..  ..  ...  ...  ..  ...       ...       ...       ...       ...       ...
534  10   7    4    4   6  ...  0.000000  0.000000  0.000000  0.000000  0.000000
535  22   9    7    4   5  ...  0.000000  0.000000  0.000000  0.000000  0.000000
536  12  11    2    3  10  ...  0.031806  0.000000  0.016057  0.000000  0.000000
537  22  14    4    7  11  ...  0.000000  0.000000  0.000000  0.000000  0.000000
538   9   7    3    1   3  ...  0.000000  0.000000  0.000000  0.000000  0.000000

[539 rows x 4035 columns]

### Add news in format of vectores is test

In [ ]:
# Create dataframe with matrix of news
dftest = pd.DataFrame(X_test_ok)

In [ ]:
# Drop news in format of words
X_test.drop(columns=['Noticias Home','Noticias Away'],inplace=True)

In [ ]:
X_test =pd.concat((X_test,dftest),ignore_index=True,axis=1)

In [ ]:
# back name for columns of historic
y = 0
for x in columns_news:
    X_test.rename(columns={y:x},inplace=True)
    y=y+1

In [ ]:
X_test

HS  AS  HST  AST  HC  ...  4030      4031      4032      4033      4034
0    11  19    6    9   2  ...   0.0  0.000000  0.000000  0.000000  0.000000
1    28   3    7    0  12  ...   0.0  0.000000  0.000000  0.000000  0.000000
2    14  22    6    4   4  ...   0.0  0.000000  0.000000  0.008867  0.000000
3     3  11    2    6  11  ...   0.0  0.000000  0.000000  0.000000  0.000000
4    15  12    9    4   2  ...   0.0  0.000000  0.000000  0.000000  0.000000
..   ..  ..  ...  ...  ..  ...   ...       ...       ...       ...       ...
226   5  17    1    5   3  ...   0.0  0.000000  0.000000  0.000000  0.004162
227  22   9    5    2   5  ...   0.0  0.000000  0.000000  0.000000  0.000000
228  23   9    4    4  12  ...   0.0  0.012719  0.023236  0.000000  0.013929
229  22   6   12    0  13  ...   0.0  0.000000  0.000000  0.000000  0.000000
230  19  12    7    4  11  ...   0.0  0.000000  0.000000  0.000000  0.000000

[231 rows x 4035 columns]

## Applying Logistic Regression

### Use Cross Validation to find best parameters

In [ ]:
y_trainu =y_train.astype('int')

In [ ]:
log_reg = LogisticRegression(random_state = 42, max_iter = 1000, multi_class = 'ovr')

# defining the search space
space = dict()
space['solver'] = ['lbfgs','newton-cg', 'liblinear']
space['penalty'] = ['l1', 'l2', 'elasticnet']
space['C'] = np.arange(10**-4, 20, 0.01)

# training the model and fitting our data to it
rscv = RandomizedSearchCV(log_reg, space, cv = 3, n_jobs = -1, n_iter = 100,verbose=2)
result = rscv.fit(X_train,y_trainu)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  37 tasks      | elapsed:   59.7s
[Parallel(n_jobs=-1)]: Done 158 tasks      | elapsed:  2.6min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  5.3min finished


In [ ]:
#best C and regularization
C = rscv.best_params_
c = C['C']
l_penalty = C['penalty']
l_solver = C['solver']

#printing c (best hyperparameter) and penalty
print("C: ", c, "\nPenalty: ", l_penalty)
print("Solver: ", l_solver)

C:  2.0401000000000002 
Penalty:  l1
Solver:  liblinear


### Training model

In [ ]:
reg_log= LogisticRegression(solver=l_solver,random_state=0,penalty= l_penalty,C=c )
reg_log.fit(X_train,y_trainu)

LogisticRegression(C=2.0401000000000002, class_weight=None, dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='auto', n_jobs=None, penalty='l1',
                   random_state=0, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

### Testing model

In [ ]:
y_testu=y_test.astype('int')

In [ ]:
predictions = reg_log.predict(X_test)
predictions2 = reg_log.predict(X_train)

In [ ]:
print(confusion_matrix(y_testu,predictions))  
print(classification_report(y_testu,predictions))  
print(accuracy_score(y_testu, predictions))
print(accuracy_score(y_trainu, predictions2))

[[85  6 14]
 [23  4 21]
 [14  8 56]]
              precision    recall  f1-score   support

           1       0.70      0.81      0.75       105
           2       0.22      0.08      0.12        48
           3       0.62      0.72      0.66        78

    accuracy                           0.63       231
   macro avg       0.51      0.54      0.51       231
weighted avg       0.57      0.63      0.59       231

0.6277056277056277
0.6957328385899815


## Using logistic regression whitout news

In [ ]:
X_train_wn = X_train[columns_news]

In [ ]:
X_test_wn = X_test[columns_news]

In [ ]:
log_reg2 = LogisticRegression(random_state = 42, max_iter = 1000, multi_class = 'ovr')

# defining the search space
space = dict()
space['solver'] = ['newton-cg', 'liblinear']
space['penalty'] = ['l1', 'l2', 'elasticnet']
space['C'] = np.arange(10**-4, 20, 0.01)

# training the model and fitting our data to it
rscv2 = RandomizedSearchCV(log_reg2, space, cv = 3, n_jobs = -1, n_iter = 100,verbose=2)
result2 = rscv2.fit(X_train_wn, y_trainu)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done 220 tasks      | elapsed:    7.0s
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:   11.1s finished


In [ ]:
#best C and regularization
C2 = rscv2.best_params_
c2 = C2['C']
l_penalty2 = C2['penalty']
l_solver2 = C2['solver']

#printing c (best hyperparameter) and penalty
print("C: ", c2, "\nPenalty: ", l_penalty2)
print("Solver: ", l_solver2)

C:  2.3001000000000005 
Penalty:  l2
Solver:  liblinear


In [ ]:
reg_log2= LogisticRegression(solver=l_solver2,random_state=0,penalty=l_penalty2,C=c2 )
reg_log2.fit(X_train_wn,y_trainu)

LogisticRegression(C=2.3001000000000005, class_weight=None, dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
predictions2 = reg_log2.predict(X_test_wn)

In [ ]:
print(confusion_matrix(y_testu,predictions2))  
print(classification_report(y_testu,predictions2))  
print(accuracy_score(y_testu, predictions2))

[[87  7 11]
 [26  2 20]
 [15  8 55]]
              precision    recall  f1-score   support

           1       0.68      0.83      0.75       105
           2       0.12      0.04      0.06        48
           3       0.64      0.71      0.67        78

    accuracy                           0.62       231
   macro avg       0.48      0.53      0.49       231
weighted avg       0.55      0.62      0.58       231

0.6233766233766234
